# Generated by Django 5.2.1 on 2025-05-16 15:10

import django.db.models.deletion
from django.db import migrations, models

import pastes.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Paste",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(default=pastes.models.generate_nanoid, max_length=21, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("expiration_datetime", models.DateTimeField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                ("burn_after_read", models.BooleanField(default=False)),
                ("syntax", models.CharField(default="plain", max_length=50)),
                ("raw_data", models.TextField()),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pastes.category")),
            ],
        ),
        migrations.CreateModel(
            name="VisitCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("paste", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pastes.paste")),
            ],
            options={
                "unique_together": {("paste",)},
            },
        ),
    ]
